# ./docker-compose.yml

version: '3.1'

services:
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 12fm03mj92
      MYSQL_DATABASE: ldock
    ports:
      - "9906:3306"
  web:
    container_name: web
    build: .
    volumes:
      # this sync our source code to the container
      - ./:/var/www/html/
    links:
      - db
    networks:
      - default
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
    - db:db
    ports:
    - 8000:80
volumes:
  persistent: