# ./docker-compose.yml

version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 12fm03mj92
      MYSQL_DATABASE: laravel
    ports:
      - "9906:3306"
  web:
    container_name: web
    build: .
    volumes:
      # this sync our source code to the container
      - /home/docker/shared/startup_docker/:/var/www/html/
    links:
      - db
    networks:
      - default
    ports:
      - "80:80"
    stdin_open: true
    tty: true
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
    - db:db
    ports:
    - 8000:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 12fm03mj92

volumes:
  persistent:
